# This is a basic workflow to help you get started with Actions

name: Website

permissions:
  pages: write
  id-token: write

# Controls when the action will run.
on:
  push:
    branches: [main] # Must be changed to `main` once released

      # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "publish-website"
  publish-website:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
        with:
          repository: Iltotore/iron
      - run: |
          git fetch --prune --unshallow --tags
          git tag -l

      - uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Build website
        run: ./millw -i docs.docJar

      - uses: actions/upload-pages-artifact@v1.0.4
        with:
          path: out/docs/docJar.dest/javadoc

      - uses: actions/deploy-pages@v1.0.10